AplikacjaLaby/Controllers/BirthController.cs
using AplikacjaLaby.Models;
using Microsoft.AspNetCore.Mvc;

namespace AplikacjaLaby.Controllers
{
    public class BirthController : Controller
    {
        public IActionResult Form()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Result([FromForm]Birth model)
        {
            if (model.IsValid())
                return View(model);
            else
                return View();
        }
    }
}

AplikacjaLaby/Controllers/BookController.cs
using AplikacjaLaby.Models;
using AplikacjaLaby.Models.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AplikacjaLaby.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class BookController : Controller
    {
        private readonly IBookService _bookService;

        public BookController(IBookService bookService)
        {
            _bookService = bookService;
        }

        //[AllowAnonymous]
        public IActionResult Index()
        {
            return View(_bookService.GetAll());
        }

        public IActionResult PagedIndex([FromQuery] int page = 1, [FromQuery] int size = 1)
        {
            return View(_bookService.FindPage(page, size));
        }

        [HttpGet]
        public IActionResult Create() //Return form
        {
            Book newBook = new();

            newBook.Owners =
                _bookService
                .GetAllOwners()
                .Select(x => new SelectListItem() { Text = $"{x.Name} {x.Surname}", Value = x.Id.ToString() }) // Transform Owner into SelectListItem using LINQ
                .ToList();

            return View(newBook);
        }

        [HttpPost] // Called from FORM - when posted
        public IActionResult Create(Book book)
        {
            if (ModelState.IsValid)
            {
                _bookService.Add(book);
                return RedirectToAction("Index");
            }
            else
            {
                book.Owners =
                    _bookService
                    .GetAllOwners()
                    .Select(x => new SelectListItem() { Text = $"{x.Name} {x.Surname}", Value = x.Id.ToString() }) // Transform Owner into SelectListItem using LINQ
                    .ToList();

                return View(book); 
            }
        }

        [HttpGet]
        public IActionResult CreateUsingApi() //Return form
        {
            return View();
        }

        [HttpPost] // Called from FORM - when posted
        public IActionResult CreateUsingApi(Book book)
        {
            if (ModelState.IsValid)
            {
                _bookService.Add(book);
                return RedirectToAction("Index");
            }
            else
            {
                return View(book);
            }
        }

        public IActionResult Delete(int id)
        {
            _bookService.Delete(id);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int? id)
        {
            var target = _bookService.GetById((int)id!);
            return View(target);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var target = _bookService.GetById((int)id!);

            if (target is null)
                RedirectToAction("Index");

            target!.Owners = 
                _bookService.GetAllOwners()
                .Select(x => new SelectListItem() { Text = $"{x.Name} {x.Surname}", Value = x.Id.ToString() })
                .ToList();

            return View(target);
        }

        [HttpPost]
        public IActionResult Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                _bookService.Update(book);
                return RedirectToAction("Index");
            }
            else
            {
                book.Owners =
                    _bookService.GetAllOwners()
                    .Select(x => new SelectListItem() { Text = $"{x.Name} {x.Surname}", Value = x.Id.ToString() })
                    .ToList();

                return View(book);
            }
        }
    }
}

AplikacjaLaby/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AplikacjaLaby</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AplikacjaLaby.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AplikacjaLaby</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Calculator">Calc (query)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Form">Calc Form</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Birth" asp-action="Form">Birth Form</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>                        
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AplikacjaLaby - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>